version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies on Ubuntu..."
      - sudo apt update -y
      - sudo apt install -y unzip curl  # unzip과 curl을 설치
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)  # ECR 로그인
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-django-app .
      - docker tag my-django-app:latest 362676892693.dkr.ecr.ap-northeast-2.amazonaws.com/my-django-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 362676892693.dkr.ecr.ap-northeast-2.amazonaws.com/my-django-app:latest
artifacts:
  files:
    - '**/*'
